add_test([=[_.Add]=]  /Users/pawkorchargin/itmo-ct-y27-s3/cpp/hw1/tests/op_tests [==[--gtest_filter=_.Add]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[_.Add]=]  PROPERTIES WORKING_DIRECTORY /Users/pawkorchargin/itmo-ct-y27-s3/cpp/hw1/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[_.Diff]=]  /Users/pawkorchargin/itmo-ct-y27-s3/cpp/hw1/tests/op_tests [==[--gtest_filter=_.Diff]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[_.Diff]=]  PROPERTIES WORKING_DIRECTORY /Users/pawkorchargin/itmo-ct-y27-s3/cpp/hw1/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[_.Mul]=]  /Users/pawkorchargin/itmo-ct-y27-s3/cpp/hw1/tests/op_tests [==[--gtest_filter=_.Mul]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[_.Mul]=]  PROPERTIES WORKING_DIRECTORY /Users/pawkorchargin/itmo-ct-y27-s3/cpp/hw1/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[_.AddBig]=]  /Users/pawkorchargin/itmo-ct-y27-s3/cpp/hw1/tests/op_tests [==[--gtest_filter=_.AddBig]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[_.AddBig]=]  PROPERTIES WORKING_DIRECTORY /Users/pawkorchargin/itmo-ct-y27-s3/cpp/hw1/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[_.MulBig]=]  /Users/pawkorchargin/itmo-ct-y27-s3/cpp/hw1/tests/op_tests [==[--gtest_filter=_.MulBig]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[_.MulBig]=]  PROPERTIES WORKING_DIRECTORY /Users/pawkorchargin/itmo-ct-y27-s3/cpp/hw1/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[_.DivInt]=]  /Users/pawkorchargin/itmo-ct-y27-s3/cpp/hw1/tests/op_tests [==[--gtest_filter=_.DivInt]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[_.DivInt]=]  PROPERTIES WORKING_DIRECTORY /Users/pawkorchargin/itmo-ct-y27-s3/cpp/hw1/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[_.DivFloat]=]  /Users/pawkorchargin/itmo-ct-y27-s3/cpp/hw1/tests/op_tests [==[--gtest_filter=_.DivFloat]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[_.DivFloat]=]  PROPERTIES WORKING_DIRECTORY /Users/pawkorchargin/itmo-ct-y27-s3/cpp/hw1/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[_.DivIntToFloat]=]  /Users/pawkorchargin/itmo-ct-y27-s3/cpp/hw1/tests/op_tests [==[--gtest_filter=_.DivIntToFloat]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[_.DivIntToFloat]=]  PROPERTIES WORKING_DIRECTORY /Users/pawkorchargin/itmo-ct-y27-s3/cpp/hw1/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  op_tests_TESTS _.Add _.Diff _.Mul _.AddBig _.MulBig _.DivInt _.DivFloat _.DivIntToFloat)
